apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-deployment-name
  name: my-deployment-name
  namespace: deployment-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app-name
  template:
    metadata:
      labels:
        app: my-app-name
      annotations:
        app_name: my-app-name			# any string denoting your app's name
		app_comp: my-component-name		# any string denoting your component's name
		env: dev 						# dev | test | uat | prod
        asi_ci_num: CI111111			# the CI number for the application
		app_ci_num: CI222222		    # the CI number for the top level component
		cost_center: '0123'				# the cost center for the team
		owning_segment: ets				# ets | can | us | asia | gf | gwam
		sec_flag: 'false'				# if true, logs have security details but does not have the ability to specify this at the event level
		kri_64: 'false'					# if true, the source/application is in KRI64 reporting scope. Generally, mark true if the app is CDI
		pii_flag: 'false'				# if true, logs have pii content but does not have the ability to specify this at the event level
      namespace: deployment-namespace
    spec:
      containers:
      - image: nginx
        name: my-container-name
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
        envFrom:
        - configMapRef:
            name: my-configmap-name
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "512Mi"
